#!/Applications/Kivy.app/Contents/Resources/python
__author__ = 'Kellan Childers'
from kivy.app import App
from userinterface import MainScreen


class RecApp(App):
    def build(self):
        return MainScreen()

if __name__ == "__main__":
    RecApp().run()
