#!/Applications/Kivy.app/Contents/Resources/python
__author__ = 'Kellan Childers'
from kivy.app import App


class RecApp(App):
    title = 'RecApp'
    kv_file = 'userinterface/mainscreen.kv'

if __name__ == "__main__":
    RecApp().run()
